//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationLocamerLDeMOg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailReserv
    {
        public int idOption { get; set; }
        public int idSejour { get; set; }
        public Nullable<int> quantite { get; set; }
        public Nullable<int> nbJour { get; set; }
    
        public virtual OptionSej OptionSej { get; set; }
        public virtual Sejour Sejour { get; set; }
    }
}
