//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationLocamerLDeMOg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailSej
    {
        public int id { get; set; }
        public int emplacement { get; set; }
        public int idSejour { get; set; }
    
        public virtual Emplacement Emplacement1 { get; set; }
        public virtual Sejour Sejour { get; set; }
    }
}
